name: Publish map artifacts

on:
  push:
    branches: [development]

permissions:
  contents: write

jobs:
  publish:
    uses: IRE-Mudlet-Mapping/CrowdmapPlatform/.github/workflows/publish-map.yml@v1
    with:
      website-directory: website
